### ISSUE TITLE
HTUPDATE Manager

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/HTAlt#43]
Since we have a new system for updating stuff, I think I also should do a manager for this.
With this manager, everyone can create/apply HTUPDATE packages, update stuff, create/apply delta packages or create HTUPDATE packages from a location.
This manager will be command-line based and can be used in any system. 
**ToDos:**
- [x] Implement un/zip feature.
- [x] Implement delta packaging.
- [x] Implement updating HTUPDATE.
- [x] Implement batch creating packages.
- [x] Test all features:
  - [x] Zipping
  - [x] Unzipping
  - [x] Creating Delta
  - [x] Applying Delta
  - [x] Updating
    - [x] Normal
    - [x] Delta
  - [x] Batch creating
-  ~~Implement adding packages to a repository and auto updating them.~~

**Comment by Haltroy** [comment]
> - Implement adding packages to a repository and auto updating them.
> 
 At first, I thought about making HTU-Man as a package manager just like the ones used in Linux distributions (such as APT, YUM, DNF, PACMAN etc.) for everything and for basic usage (instead of just a distribution of binary files) so there's no plan to make it require administration privileges. 
But that would make it easier for other malicious programs to take advantage of HTU-Man's not requiring administrative privileges to remove every repository or add more bad repositories to slow down computer. And users can still update their stuff with `update` command instead (well yes, users have to manually do for each HTUPDATE file now but removing or changing the file itself is not in my concern as it is just a file deletion/change and the operating system or the user can be accountable for that).
Most of the features listed here is almost ready, except the creation of packages which is the least clear thing in this list so I can easily explain it:
- When running HTU-Man with `create` option, you also have to enter 2 more options (In order); the main folder and the output folder.
- The main folder should contain the main HTUPDATE file and subfolder for each version and subfolders containing data for each architecture inside the version. Everything is configured from that HTUPDATE file.
- The output folder will contain all the packages (still in their original folder, except all data inside of it is compressed into 1 file) after running the manager with enough information.
- You also can tell which HTUPDATE to use by just simply telling the name of the HTUPDATE file (either with file extension or not) as the last option

**Comment by Haltroy** [comment]
Everyting (except batch creating since it's not done yet) tested and fixed.

**Comment by Haltroy** [comment]
I tested everything, but I think I should add some more options to `update`.
