### ISSUE TITLE
Delta Improvments

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/HTAlt#44]
> The testing environment consist of simple files with simple changes to them, which means it might not be the case for actual use.

 > It usually should take more smaller but the current system has 3 flaws which needs to be fixed in order to make delta packages smaller than the normal packaging:
 > - Changes to a file is not stored in actual bytes, rather it was stored as base64 which is way bigger than the bytes themselves. 
 > - The Start, Length and Trim properties are stored as string instead of integer, which integers are more smaller than strings. 
 > - The entire file is actually a XML file, so it obviously takes a size but it's only noticeable on small files. 

 > So, I have to make a completely new type of storing them instead of just storing inside of XML file and compressing it with GZip. 

_Above originally posted by @Haltroy in https://github.com/Haltroy/HTAlt/issues/42#issuecomment-901333026_

 > Currently, Delta system uses byte arrays which limits everything to 2GiB (2130702268 bytes). In order to fix this, I need to work on changing everything to stream to increase this size to 2^63 (9223372036854775807 bytes). Which is 8388608 TiB. Unless the 128-bit streams are a thing, this change will last more longer.

 > Yes, I am still looking for something to divide a string, an integer and a group of bytes in a file. 

_Above originally posted by @Haltroy in https://github.com/Haltroy/HTAlt/issues/42#issuecomment-907884928_

# ToDos:
 - [x] Convert Creating Delta from byte[] to Stream
 - [x] Convert Applying Delta from byte[] to Stream
 - [x] Test new format.

**Comment by Haltroy** [comment]
Currently, everything works so far, except "Change" feature, which writes zeroes before the difference. I need to focus on that and then I can finally close this issue.
