### ISSUE TITLE
HTUPDATE - Save Downloads 

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/HTAlt#71]
This waa the actual implementation for HTUPDATE but it was replaced with "just download them to a memory stream then use that stream instead of file stream" because the file stream will give a weird no-permissions exception out of nowhere. However, this method now makes HTUPDATE to download the files from the web every time if it fails.

We can instead, use a file stream with the combination of a memory stream so the file will be saved to a temporary location if HTUPDATE or system crashes and the installation can continue from there if file checks are valid and file downloaded successfully.
**TODOs:**
- [ ] Save files to a temporary location with a FileStream.
- [ ] Check if file that was saved is fine and don't download it again.
- [ ] Do this for the HTUPDATE file too.
- [ ] Add asynchronous auto-sync feature.
